# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(max_length=2)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='configuration_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(max_length=2)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='configurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('motherboard', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('raidcard', models.CharField(max_length=100)),
                ('disk1', models.CharField(max_length=100)),
                ('disk2', models.CharField(max_length=100)),
                ('default', models.CharField(max_length=100)),
                ('status', models.IntegerField(max_length=2)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hardware_accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(max_length=2)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='configuration_lists',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.configurations'),
        ),
        migrations.AddField(
            model_name='configuration_lists',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='servers.base_types'),
        ),
        migrations.AddField(
            model_name='configuration_lists',
            name='offline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline', to='servers.base_types'),
        ),
        migrations.AddField(
            model_name='configuration_lists',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='servers.base_types'),
        ),
        migrations.AddField(
            model_name='configuration_lists',
            name='realtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime', to='servers.base_types'),
        ),
        migrations.AddField(
            model_name='configuration_lists',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='servers.base_types'),
        ),
    ]
