# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_types',
            name='status',
            field=models.SmallIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='base_types',
            name='type',
            field=models.SmallIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='configuration_lists',
            name='status',
            field=models.SmallIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='status',
            field=models.SmallIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='hardware_accessories',
            name='status',
            field=models.SmallIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='hardware_accessories',
            name='type',
            field=models.SmallIntegerField(max_length=2),
        ),
    ]
