# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20180704_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_types',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='base_types',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configuration_lists',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='configuration_lists',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hardware_accessories',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hardware_accessories',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
