# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20180704_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base_types',
            options={'verbose_name': '\u57fa\u7840\u7c7b\u578b', 'verbose_name_plural': '\u57fa\u7840\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='configuration_lists',
            options={'verbose_name': '\u670d\u52a1\u5668\u6e05\u5355', 'verbose_name_plural': '\u670d\u52a1\u5668\u6e05\u5355'},
        ),
        migrations.AlterModelOptions(
            name='configurations',
            options={'verbose_name': '\u670d\u52a1\u5668\u914d\u7f6e', 'verbose_name_plural': '\u670d\u52a1\u5668\u914d\u7f6e'},
        ),
        migrations.AlterModelOptions(
            name='hardware_accessories',
            options={'verbose_name': '\u670d\u52a1\u5668\u786c\u4ef6\u914d\u4ef6', 'verbose_name_plural': '\u670d\u52a1\u5668\u786c\u4ef6\u914d\u4ef6'},
        ),
        migrations.AlterField(
            model_name='configurations',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='servers.hardware_accessories'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='default',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default', to='servers.hardware_accessories'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='disk1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk1', to='servers.hardware_accessories'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='disk2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk2', to='servers.hardware_accessories'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='servers.hardware_accessories'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='servers.hardware_accessories'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='raidcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raidcard', to='servers.hardware_accessories'),
        ),
    ]
