# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20180704_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='servers.hardware_accessories'),
        ),
    ]
