# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_auto_20180704_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration_lists',
            name='configuration',
        ),
        migrations.AddField(
            model_name='configuration_lists',
            name='configuration',
            field=models.ManyToManyField(to='servers.configurations'),
        ),
    ]
