# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_base_types_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_types',
            name='tags',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='configuration_lists',
            unique_together=set([('platform', 'device', 'realtime', 'offline')]),
        ),
    ]
