# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0011_auto_20180705_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='category',
            field=models.SmallIntegerField(default=0),
        ),
    ]
