# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0012_configurations_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_types',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration_lists',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configurations',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hardware_accessories',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
