# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0013_auto_20180707_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='count',
            field=models.SmallIntegerField(default=1),
        ),
    ]
