# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0014_configurations_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurations',
            name='count',
        ),
        migrations.AddField(
            model_name='configuration_lists',
            name='bandwith',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, to='servers.hardware_accessories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration_lists',
            name='count',
            field=models.SmallIntegerField(default=1),
        ),
    ]
