# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0015_auto_20180709_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='count', to='servers.hardware_accessories'),
            preserve_default=False,
        ),
    ]
