# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0016_configurations_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_types',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='configuration_lists',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hardware_accessories',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
