# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0018_auto_20180709_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='cpu',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='servers.hardware_accessories'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='default',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='default', to='servers.hardware_accessories'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='disk1',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='disk1', to='servers.hardware_accessories'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='disk2',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='disk2', to='servers.hardware_accessories'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='memory',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='servers.hardware_accessories'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='motherboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='servers.hardware_accessories'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='raidcard',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='raidcard', to='servers.hardware_accessories'),
        ),
    ]
