# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0019_auto_20180712_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='count',
            field=models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, related_name='count', to='servers.hardware_accessories'),
        ),
    ]
