# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0020_auto_20180712_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration_lists',
            name='service',
        ),
        migrations.AddField(
            model_name='configuration_lists',
            name='service',
            field=models.ManyToManyField(related_name='service', to='servers.base_types'),
        ),
    ]
